import Database from "better-sqlite3";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { addContestScoreEntry, addManualSalesEntry, correctSalesCheck, getContestSalesData, getServerChecks, importSalesCsv } from "./sales-data";

function fixture() { const db = new Database(":memory:"); db.exec(readFileSync(new URL("./schema.sql", import.meta.url), "utf8")); db.exec("INSERT INTO servers VALUES (1, 'Avery Moss', '#d97706', 1)"); db.exec("INSERT INTO menu_items VALUES (1, 'Ember Corn Cups', 'app', 8, 0)"); return db; }
describe("sales data entry", () => {
  it("imports reconciled itemized sales and keeps an audit trail", () => { const db = fixture(); const csv = "check_reference,opened_at,server_name,party_size,subtotal,item_name,qty,price_each,note\nA-1,2026-07-13T18:00:00.000Z,Avery Moss,2,8,Ember Corn Cups,1,8,uploaded shift"; const result = importSalesCsv(db, "shift.csv", csv); expect(result).toEqual({ importedChecks: 1, importedRows: 1 }); expect(db.prepare("SELECT source_type, is_itemized FROM sales_entry_audit").get()).toEqual({ source_type: "imported", is_itemized: 1 }); expect(() => importSalesCsv(db, "retry.csv", csv)).toThrow("already imported"); });
  it("tags manual corrections separately from imported sales", () => { const db = fixture(); addManualSalesEntry(db, { serverId: 1, openedAt: "2026-07-13T18:00:00.000Z", partySize: 2, subtotal: 32, note: "Corrected closeout" }); expect(db.prepare("SELECT source_type, note FROM sales_entry_audit").get()).toEqual({ source_type: "manual", note: "Corrected closeout" }); });
  it("corrects an existing check, replaces its items, and preserves the before value", () => { const db = fixture(); db.exec("INSERT INTO checks VALUES (9, 1, '2026-07-13T18:00:00.000Z', 2, 8); INSERT INTO check_items VALUES (1, 9, 1, 1, 8)"); correctSalesCheck(db, { checkId: 9, serverId: 1, openedAt: "2026-07-13T19:00:00.000Z", partySize: 3, subtotal: 16, note: "Added missed appetizer", items: [{ menuItemId: 1, qty: 2, priceEach: 8 }] }); expect(db.prepare("SELECT party_size, subtotal FROM checks WHERE id = 9").get()).toEqual({ party_size: 3, subtotal: 16 }); expect(db.prepare("SELECT qty FROM check_items WHERE check_id = 9").get()).toEqual({ qty: 2 }); expect(db.prepare("SELECT source_type, is_itemized FROM sales_entry_audit WHERE check_id = 9").get()).toEqual({ source_type: "corrected", is_itemized: 1 }); expect(db.prepare("SELECT before_json FROM sales_corrections WHERE check_id = 9").get()).toMatchObject({ before_json: expect.stringContaining('"subtotal":8') }); });
  it("rejects inconsistent and unreconciled grouped rows", () => { const db = fixture(); expect(() => importSalesCsv(db, "bad.csv", "check_reference,opened_at,server_name,party_size,subtotal,item_name,qty,price_each,note\nA-1,2026-07-13T18:00:00.000Z,Avery Moss,2,10,Ember Corn Cups,1,8,note\nA-1,2026-07-13T18:00:00.000Z,Avery Moss,3,10,Ember Corn Cups,1,8,note")).toThrow("inconsistent"); });
  it("paginates a server's checks for the inline drawer", () => { const db = fixture(); for (let id = 1; id <= 12; id += 1) db.prepare("INSERT INTO checks VALUES (?, 1, ?, 2, 8)").run(id, `2026-07-${String(id).padStart(2, "0")}T18:00:00.000Z`); const data = getServerChecks(db, 1, 2); expect(data).toMatchObject({ page: 2, pageCount: 2, pageSize: 10, totalChecks: 12 }); expect(data.checks.map((check) => check.id)).toEqual([2, 1]); });
  it("records active contest item sales without creating a check", () => { const db = fixture(); const config = JSON.stringify({ goals: [], games: [{ id: "race", type: "sales_race", metric: { metric: "item_count", menu_item_id: 1 } }] }); db.prepare("INSERT INTO contests VALUES (1, 'Corn Cup Contest', '2026-07-13', ?, 'active', 'manual')").run(config); expect(getContestSalesData(db)?.targets).toEqual([{ menuItemId: 1, name: "Ember Corn Cups", price: 8 }]); addContestScoreEntry(db, { serverId: 1, menuItemId: 1, quantity: 4 }); expect(db.prepare("SELECT COUNT(*) AS count FROM checks").get()).toEqual({ count: 0 }); expect(db.prepare("SELECT contest_id, server_id, menu_item_id, quantity, note FROM contest_score_entries").get()).toEqual({ contest_id: 1, server_id: 1, menu_item_id: 1, quantity: 4, note: "Live contest tally" }); });
});
