"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { getSalesDataPageData } from "../lib/db/sales-data";

type Data = ReturnType<typeof getSalesDataPageData>;
type Check = Data["recentChecks"][number];
type ItemLine = { menuItemId: string; qty: string; priceEach: string };

function localDateTime(value: string) { return value.slice(0, 16); }
function linesFor(check: Check): ItemLine[] { return check.items.map((item) => ({ menuItemId: String(item.menu_item_id), qty: String(item.qty), priceEach: String(item.price_each) })); }
function formatMetric(value: number, metricId: string) { return metricId.includes("_pct") || metricId.startsWith("attach_rate") ? `${(value * 100).toFixed(1)}%` : `$${value.toFixed(2)}`; }

export function SalesDataManager({ data }: { data: Data }) {
  const router = useRouter();
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [search, setSearch] = useState(data.query);
  const [selected, setSelected] = useState<Check | null>(null);
  const [newCheck, setNewCheck] = useState(false);
  const [serverId, setServerId] = useState("");
  const [openedAt, setOpenedAt] = useState("");
  const [partySize, setPartySize] = useState("");
  const [subtotal, setSubtotal] = useState("");
  const [note, setNote] = useState("");
  const [items, setItems] = useState<ItemLine[]>([]);

  function chooseCheck(check: Check) { setNewCheck(false); setSelected(check); setServerId(String(check.server_id)); setOpenedAt(localDateTime(check.opened_at)); setPartySize(String(check.party_size)); setSubtotal(String(check.subtotal)); setNote(check.note); setItems(linesFor(check)); setMessage(""); }
  function startNewCheck(forServerId = data.servers[0]?.id) { setSelected(null); setNewCheck(true); setServerId(String(forServerId ?? "")); setOpenedAt(new Date().toISOString().slice(0, 16)); setPartySize("1"); setSubtotal("0"); setNote("Live manager entry"); setItems([]); setMessage(""); window.setTimeout(() => document.getElementById("sales-entry-editor")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }
  function updateItem(index: number, field: keyof ItemLine, value: string) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item)); }
  function addItem() { setItems((current) => [...current, { menuItemId: String(data.menuItems[0]?.id ?? ""), qty: "1", priceEach: String(data.menuItems[0]?.price ?? "0") }]); }
  function removeItem(index: number) { setItems((current) => current.filter((_, itemIndex) => itemIndex !== index)); }
  function pageHref(page: number) { const params = new URLSearchParams(); if (data.query) params.set("query", data.query); params.set("page", String(page)); return `/data?${params}`; }

  async function upload() { if (!file) return; setBusy(true); const csv = await file.text(); const response = await fetch("/api/sales-data/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fileName: file.name, csv }) }); const result = await response.json().catch(() => null) as { importedChecks?: number; error?: string } | null; setBusy(false); setMessage(response.ok ? `Imported ${result?.importedChecks} checks from ${file.name}.` : result?.error ?? "Import failed."); if (response.ok) router.refresh(); }
  async function saveCheck() { if (!selected && !newCheck) return; setBusy(true); const response = await fetch(selected ? `/api/sales-data/checks/${selected.id}` : "/api/sales-data/manual", { method: selected ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serverId: Number(serverId), openedAt: new Date(openedAt).toISOString(), partySize: Number(partySize), subtotal: Number(subtotal), note, items: items.map((item) => ({ menuItemId: Number(item.menuItemId), qty: Number(item.qty), priceEach: Number(item.priceEach) })) }) }); const result = await response.json().catch(() => null) as { error?: string } | null; setBusy(false); setMessage(response.ok ? selected ? `Check #${selected.id} corrected and marked Edited.` : "New check saved and marked Manual." : result?.error ?? "Could not save this check."); if (response.ok) { setSelected(null); setNewCheck(false); router.refresh(); } }

  const editor = (selected || newCheck) && <section className="data-card correction-editor" id="sales-entry-editor"><div><p className="eyebrow">{selected ? `Correct check #${selected.id}` : "New sales entry"}</p><h2>{selected ? "Correct the source record" : "Add live sales"}</h2><p>{selected ? "The previous values and reason are retained in correction history." : "This creates an auditable manual check. Item detail immediately updates item and attachment gameboards."}</p></div><label>Server<select value={serverId} onChange={(event) => setServerId(event.target.value)}>{data.servers.map((server) => <option value={server.id} key={server.id}>{server.name}</option>)}</select></label><label>Opened at<input type="datetime-local" value={openedAt} onChange={(event) => setOpenedAt(event.target.value)} /></label><div className="manual-numbers"><label>Party size<input type="number" min="1" value={partySize} onChange={(event) => setPartySize(event.target.value)} /></label><label>Subtotal<input type="number" min="0" step="0.01" value={subtotal} onChange={(event) => setSubtotal(event.target.value)} /></label></div><label>{selected ? "Reason for correction" : "Entry note"}<input value={note} onChange={(event) => setNote(event.target.value)} placeholder={selected ? "Why was this changed?" : "Why is this being entered manually?"} /></label><div className="item-editor"><div className="item-editor-heading"><h3>Items sold</h3><button className="button secondary" type="button" onClick={addItem}>Add item</button></div>{items.length ? items.map((item, index) => <div className="item-line" key={`${index}-${item.menuItemId}`}><select value={item.menuItemId} onChange={(event) => { const menuItem = data.menuItems.find((menu) => menu.id === Number(event.target.value)); updateItem(index, "menuItemId", event.target.value); if (menuItem) updateItem(index, "priceEach", String(menuItem.price)); }}>{data.menuItems.map((menuItem) => <option value={menuItem.id} key={menuItem.id}>{menuItem.name}</option>)}</select><input type="number" min="1" step="1" value={item.qty} aria-label="Quantity" onChange={(event) => updateItem(index, "qty", event.target.value)} /><input type="number" min="0" step="0.01" value={item.priceEach} aria-label="Price each" onChange={(event) => updateItem(index, "priceEach", event.target.value)} /><button className="button secondary" type="button" onClick={() => removeItem(index)}>Remove</button></div>) : <p className="empty-items">No item detail yet. Add menu items to support item-based games and metrics.</p>}</div><div className="designer-actions"><button className="button" disabled={busy} onClick={saveCheck}>{selected ? "Save corrected check" : "Save sales entry"}</button><button className="button secondary" disabled={busy} onClick={() => { setSelected(null); setNewCheck(false); }}>Cancel</button></div></section>;

  return <section className="data-workspace">
    <section className="server-performance-panel">
      <div className="data-table-heading"><div><p className="eyebrow">Server performance</p><h2>Live scores by server</h2><p>Scores are calculated from sales records. Enter sales or correct a check to update them; SIM keeps the source and change history.</p></div></div>
      <div className="board-table-wrap"><table className="server-performance-table"><thead><tr><th>Server</th>{data.performanceMetrics.map((metric) => <th key={metric.id}>{metric.label}</th>)}<th>Goals</th><th>Daily wins</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{data.serverPerformance.map((server) => <tr key={server.id}><td><span className="avatar" style={{ backgroundColor: server.color }}>{server.name.slice(0, 1)}</span><strong>{server.name}</strong>{server.edited && <span className="edited-tag">Edited</span>}</td>{data.performanceMetrics.map((metric) => <td className="metric-value" key={`${server.id}-${metric.id}`}>{formatMetric(server.values[metric.id], metric.id)}</td>)}<td><strong>{server.qualifications.filter(Boolean).length}/{data.contestGoalCount}</strong></td><td><span className="wins">{server.dailyWins}</span></td><td><div className="table-actions"><button className="button small" onClick={() => startNewCheck(server.id)}>Enter sales</button><button className="text-button" onClick={() => { setSearch(server.name); router.push(`/data?query=${encodeURIComponent(server.name)}&page=1`); }}>Checks</button></div></td></tr>)}</tbody></table></div>
    </section>
    <div className="data-card"><p className="eyebrow">Import a sheet</p><h2>Bring in sales rows.</h2><p>Export a CSV from Excel or Google Sheets, match the template columns, then import it here. Add item rows when you want item-based games and metrics.</p><a className="button secondary" href="/api/sales-data/template">Download CSV template</a><input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><button className="button" disabled={!file || busy} onClick={upload}>Import sales CSV</button></div>
    <div className="data-card"><p className="eyebrow">Live entry</p><h2>Enter sales during service</h2><p>Record itemized sales when the source system is delayed or the contest needs a live update.</p><button className="button" onClick={() => startNewCheck()}>Add sales entry</button></div>
    <div className="data-card data-history"><p className="eyebrow">Data history</p><a href="/api/sales-data/export">Export current sales CSV</a><p><strong>{data.manualCount}</strong> corrected checks in the active dataset.</p>{data.imports.length ? <ul>{data.imports.map((entry) => <li key={`${entry.file_name}-${entry.imported_at}`}>{entry.file_name} · {entry.row_count} rows</li>)}</ul> : <p>No imported sheets yet.</p>}</div>
    {editor}
    <section className="current-data-table"><div className="data-table-heading"><div><p className="eyebrow">Current sales data</p><h2>{data.totalChecks.toLocaleString()} matching checks</h2><p>Select any check to correct its sales, server, timing, and item lines.</p></div><form className="data-search" onSubmit={(event) => { event.preventDefault(); const params = new URLSearchParams(); if (search.trim()) params.set("query", search.trim()); params.set("page", "1"); router.push(`/data?${params}`); }}><label className="sr-only" htmlFor="sales-search">Search current sales</label><input id="sales-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search check, server, item, or note" /><button className="button" type="submit">Search</button></form></div><div className="board-table-wrap"><table><thead><tr><th>When</th><th>Server</th><th>Party</th><th>Subtotal</th><th>Items</th><th>Source</th><th>Note</th><th><span className="sr-only">Edit</span></th></tr></thead><tbody>{data.recentChecks.length ? data.recentChecks.map((check) => <tr key={check.id}><td>{new Date(check.opened_at).toLocaleString()}</td><td><strong>{check.server_name}</strong></td><td>{check.party_size}</td><td>${check.subtotal.toFixed(2)}</td><td>{check.is_itemized ? `${check.item_rows} rows` : "Check only"}</td><td><span className={`source-tag ${check.source_type}`}>{check.source_type}</span></td><td>{check.note || "—"}</td><td><button className="button table-action" onClick={() => chooseCheck(check)}>Edit</button></td></tr>) : <tr><td colSpan={8}>No checks match that search.</td></tr>}</tbody></table></div><nav className="data-pagination" aria-label="Sales data pages"><span>Page {data.page} of {data.pageCount}</span><div>{data.page > 1 && <a className="button secondary" href={pageHref(data.page - 1)}>Previous</a>}{data.page < data.pageCount && <a className="button secondary" href={pageHref(data.page + 1)}>Next</a>}</div></nav></section>
    {message && <p className="designer-message" role="status">{message}</p>}
  </section>;
}
